import { useMemo, useState } from "react";
import { WButton, WCard, WChip } from "@wego/ui";
import { PageHeader } from "../../components/layout/PageHeader";
import { SyncNotice } from "../../components/layout/States";
import { useAppStore } from "../../store/use-app-store";
import { useLifeRecords } from "./life-api";

type TaskFilter = "all" | "mine" | "partner" | "free";
export function TasksPage() {
  const { records, command, busy, loading, error, retry } = useLifeRecords("task");
  const meId = useAppStore(state => state.me?.id ?? "local-preview");
  const [filter, setFilter] = useState<TaskFilter>("all"); const [title, setTitle] = useState(""); const [due, setDue] = useState("");
  const tasks = useMemo(() => records.filter(record => { const assignee = record.data.assigneeId; const mine = assignee === meId || assignee === "local-preview"; if (filter === "mine") return mine; if (filter === "partner") return Boolean(assignee) && !mine; if (filter === "free") return !assignee; return true; }).sort((a, b) => Number(a.data.status === "done") - Number(b.data.status === "done")), [filter, meId, records]);
  const active = tasks.filter(task => task.data.status !== "done"); const completed = tasks.filter(task => task.data.status === "done");
  const addTask = () => { const cleanTitle = title.trim(); if (!cleanTitle) return; void command({ type: "put", id: `task-${Date.now()}`, kind: "task", data: { title: cleanTitle, ...(due ? { due } : {}), assigneeId: null, status: "open", repeat: "none", description: "" }, expectedRevision: 0 }); setTitle(""); setDue(""); };
  const renderTask = (task: typeof tasks[number]) => { const done = task.data.status === "done"; const mine = task.data.assigneeId === meId || task.data.assigneeId === "local-preview"; const partnerTask = Boolean(task.data.assigneeId) && !mine; return <WCard key={task.id} tone={done ? "cream" : mine ? "mint" : partnerTask ? "peach" : "paper"} className={`life-row task-row ${done ? "is-done" : ""}`}><button type="button" className="task-check" aria-label={done ? "Выполнено" : `Выполнить: ${String(task.data.title)}`} disabled={busy || done} onClick={() => void command({ type: "complete", id: task.id, expectedRevision: task.revision })}>{done ? "✓" : ""}</button><div className="life-row__body"><div className="life-title">{String(task.data.title)}</div><small>{task.data.due ? `до ${task.data.due}` : "без срока"} · {mine ? "взял(а) ты" : partnerTask ? "взял(а) партнёр" : "свободно"}</small></div>{!mine && !partnerTask && !done && <WButton size="sm" variant="secondary" loading={busy} onClick={() => void command({ type: "claimTask", id: task.id, expectedRevision: task.revision })}>Беру</WButton>}</WCard>; };
  return <div className="app-page life-page"><PageHeader eyebrow="Общий ритм" title="Дела" description="Свободные задачи, которые можно взять на себя одним касанием" action={<WButton size="sm" onClick={() => document.getElementById("new-task")?.focus()}>+ Дело</WButton>} /><SyncNotice loading={loading} error={error} onRetry={retry} /><div className="filter-row screen-padding">{([["all", "Все"], ["mine", "Мои"], ["partner", "Партнёра"], ["free", "Свободные"]] as const).map(([id, label]) => <WChip key={id} active={filter === id} onClick={() => setFilter(id)}>{label}{id === "all" ? ` · ${tasks.length}` : ""}</WChip>)}</div><div className="screen-padding stack">{active.length > 0 && <div className="task-group-label">В работе · {active.length}</div>}{active.map(renderTask)}{completed.length > 0 && <div className="task-group-label">Завершено · {completed.length}</div>}{completed.map(renderTask)}{!loading && tasks.length === 0 && <WCard tone="cream"><div className="life-title">Здесь пока пусто</div><p>Добавьте первую задачу или выберите другой фильтр.</p></WCard>}<WCard tone="cream" className="life-form"><div className="w-mono-caps">Новая задача</div><label className="sr-only" htmlFor="new-task">Название задачи</label><input id="new-task" value={title} onChange={event => setTitle(event.target.value)} onKeyDown={event => { if (event.key === "Enter") addTask(); }} placeholder="Что нужно сделать?" /><label className="date-field">Срок <input aria-label="Срок задачи" type="date" value={due} onChange={event => setDue(event.target.value)} /></label><WButton size="sm" disabled={!title.trim() || busy} loading={busy} onClick={addTask}>Добавить</WButton></WCard></div></div>;
}
